H2 데이터베이스를 연결하기
f-lab-edu/HelpU pull request #8
Opened 2023-03-21 06:35 UTC by Geol2

### 이슈 내용
- [ ] SpringBoot 실행 시, H2 데이터베이스가 실행되게 만들기
- [ ] DDL, DML 스크립트 작성
- [ ] 데이터 확인

2023-03-26 15:38 UTC, f-lab-jd requested changes
리뷰드린 내용만 한번 확인부탁드립니다!

2023-03-26 15:38 UTC, f-lab-jd commented on build.gradle
> +	developmentOnly 'org.springframework.boot:spring-boot-devtools'
@Geol2  devtools 를 사용하는 목적은 무엇인가요~?

2023-03-26 15:38 UTC, f-lab-jd commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
@Geol2 위 두개 라이브러리를 추가하신 이유가 궁금합니다.

2023-03-26 15:38 UTC, f-lab-jd commented on src/main/resources/application.yml
> +    open-in-view: false
@Geol2  MYBATIS 를 사용하기로 했는데, JPA 를 의존하신 이유가 궁금합니다!
불필요한 JPA 의존은 제거하는 방식으로 진행 부탁드립니다.

2023-03-30 02:35 UTC, Geol2 commented on src/main/resources/application.yml
> +    open-in-view: false
jpa 부분은 제거하도록 하겠습니다.

2023-03-30 02:38 UTC, Geol2 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
<img width="926" alt="스크린샷 2023-03-30 11 26 17" src="https://user-images.githubusercontent.com/20119461/228713001-cf5ce723-b2dd-4e3f-a8a4-01e552035c94.png">

h2 데이터베이스에 접속하기 위해서 jdbc는 필요해보이는데 어떨까요??

2023-03-30 02:38 UTC, Geol2 commented on build.gradle
> +	developmentOnly 'org.springframework.boot:spring-boot-devtools'
스프링에서 정적 파일이나 설정 파일이 변했을 때, 재시작이 필요없이 새로고침만하면 되는 편한 기능이라고 합니다.
필요없는 부분이라면 삭제하도록 하겠습니다.

2023-04-05 11:46 UTC, closed without merging